### ISSUE TITLE
Player information

### ISSUE THREAD

**Issue by rooooose-b** [Alathra/AlathraSkills#64]
Send feedback and information to the player as action bars and/or sounds when they 

1. Gain a skill point
2. Activate a skill/a skill fires
3. When cooldown for skills runs out(?)

**Comment by ShermansWorld** [comment]
Implemented player feedback on skill point gain  
https://github.com/Alathra/AlathraSkills/pull/70/commits/8f29e85fe4709af28bd756e0d5004ef35dc794cf

**Comment by ShermansWorld** [comment]
Implemented player feedback for cooldown expiring on active skills
https://github.com/Alathra/AlathraSkills/pull/73/commits/5819bb2b0289b7bae03daa5f658f436e95286192
