### ISSUE TITLE
Relicense

### ISSUE THREAD

**Issue by darksaid98** [Alathra/AlathraSkills#76]
**Is your feature request related to a problem? Please describe.**
Please re-license the repository under whatever suits your needs the best. It currently sports an `MIT No Attribution` license in my name :)

https://choosealicense.com/appendix/

**Comment by rooooose-b** [comment]
[126be17](https://github.com/Alathra/AlathraSkills/commit/126be172ec4a310d3bc63fc147b402ee741dfaea)
